#!/usr/bin/env python3
from collections import namedtuple

Library = namedtuple('Library',
                     ['name', 'files_of_interest'])

libraries = [
    Library('boringssl', [
            "include/openssl/ssl.h",
            "ssl/internal.h",
            "ssl/ssl_lib.cc",
            "ssl/handshake_client.cc",
            "ssl/extensions.cc",
            "ssl/handshake_server.cc",
            "ssl/test/bssl_shim.cc",
            "ssl/ssl_test.cc",
            "include/openssl/x509.h",
            "ssl/ssl_x509.cc",
            "ssl/s3_lib.cc",
            "ssl/handshake.cc",
            "ssl/ssl_session.cc",
            "ssl/s3_both.cc",
            "ssl/ssl_cipher.cc",
            "ssl/ssl_cert.cc",
            "include/openssl/base.h",
            "ssl/tls13_server.cc"]),
    Library('brotli',
            ['c/common/platform.h',
             'c/enc/encode.c',
             'c/enc/brotli_bit_stream.c',
             'c/dec/decode.c']),
    Library('curl',
            ['lib/http.c',
             'lib/ftp.c',
             'lib/smtp.c']),
    Library('fatfs',
            ['source/ff.c']),
    Library('flac',
            ['src/libFLAC/stream_encoder.c',
             'src/libFLAC/stream_decoder.c',
             'src/flac/encode.c',
             'src/flac/decode.c']),
    Library('fmt',
            ['src/os.cc',
             'src/fmt.cc']),
    Library('freetype',
            ['src/base/ftobjs.c',
             'src/truetype/ttgload.c',
             'src/truetype/ttinterp.c',
             'src/type1/t1load.c',
             'src/raster/ftraster.c']),
    Library('harfbuzz',
            ['src/hb-ot-layout.cc',
             'src/hb-ot-shape.cc',
             'src/hb-buffer.cc',
             'src/hb-font.cc']),
    Library('libjpeg-turbo',
            ['jcarith.c',
             'jchuff.c',
             'jdhuff.c',
             'turbojpeg.c']),
    Library('libnsgif',
            ['src/gif.c',
             'src/lzw.c']),
    Library('libpng',
            ['png.c',
             'png.h']),
    Library('libuv',
            ['src/uv-common.c',
             'src/uv-common.h',
             'src/unix/linux.c',
             'src/unix/core.c']),
    Library('lua',
            ['lvm.c',    # Lua Virtual Machine
             'lapi.c',   # Lua API
             'lgc.c']),  # Lua Garbage Collector
    Library('minizip-ng',
            ['minizip.c',
             'mz_zip.c']),
    Library('openjpeg',
            ['src/lib/openjp2/j2k.c',
             'src/lib/openjpip/jp2k_decoder.c',
             'src/lib/openjpip/jp2k_encoder.c']),
    Library('pcre2',
            ['src/pcre2_compile.c',
             'src/pcre2_match.c']),
    Library('tinyxml2',
            ['tinyxml2.h',
             'tinyxml2.cpp']),
    Library('xxHash',
            ['xxhash.h',
             'xxh3.h',
             'xxhash.c']),
    Library('xz',
            ['src/liblzma/api/lzma/block.h',
             'src/liblzma/common/stream_decoder.c',
             'src/liblzma/common/stream_encoder.c',
             'src/liblzma/common/block_decoder.c',
             'src/liblzma/common/block_encoder.c',
             'src/liblzma/lz/lz_decoder.c',
             'src/liblzma/lz/lz_encoder.c',
             'src/liblzma/lzma/lzma_decoder.c',
             'src/liblzma/lzma/lzma_encoder.c',
             'src/liblzma/rangecoder/range_decoder.h',
             'src/xz/coder.c']),
    Library('zlib',
            ['deflate.c',
             'deflate.h',
             'inflate.c',
             'gzlib.c']),
    Library('zstd',
            ['lib/zstd.h',
             'lib/common/fse.h',
             'lib/common/zstd_internal.h',
             'lib/compress/zstd_compress.c',
             'lib/decompress/zstd_decompress.c']),
]

# vim:set expandtab tabstop=4 shiftwidth=4 softtabstop=4 nowrap:
